version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'tele-collect'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'

  tele-collect-back:
    build: ./tele-collect-back
    container_name: tele-collect-back
    restart: always

  tele-collect-front:
    build: ./tele-collect-front
    container_name: tele-collect-front
    restart: always
    
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tele-collect-back
      - tele-collect-front
