version: "3"
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5436:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "tele-collect-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  tele-collect-back:
    build: ./tele-collect-back
    container_name: tele-collect-back
    restart: always
    depends_on:
      - postgres

  tele-collect-front:
    build: ./tele-collect-front
    container_name: tele-collect-front
    restart: always
    environment:
      - API_BASE_URL=http://backend:3000
    depends_on:
      - tele-collect-back

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

volumes:
  postgres:
  caddy-data:
  caddy-config:
