version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    networks:
      - tele-collect

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - tele-collect

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - tele-collect

networks:
  tele-collect: